"""fresh migration

Revision ID: bec42e052bc4
Revises: 
Create Date: 2025-05-18 12:31:08.488948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec42e052bc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_on', sa.DateTime(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
        # Add explicit constraint name
        batch_op.create_foreign_key('fk_images_report_id', 'reports', ['report_id'], ['id'])
        batch_op.drop_column('upload_date')
        batch_op.drop_column('analysis_date')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_used', sa.String(length=50), nullable=True))
        batch_op.alter_column('findings',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('pdf_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('pdf_filename')
        batch_op.drop_column('recommendations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendations', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pdf_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.TEXT(), nullable=True))
        batch_op.alter_column('pdf_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('findings',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('model_used')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('gender')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('upload_date', sa.DATETIME(), nullable=True))
        # Use the same constraint name as in upgrade
        batch_op.drop_constraint('fk_images_report_id', type_='foreignkey')
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('uploaded_on')
        batch_op.drop_column('report_id')

    # ### end Alembic commands ###